package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type fieldInfo struct {
	Name        string
	Kind        string
	ZeroVal     string
	IsPrimitive bool
}

type structInfo struct {
	Name   string
	Fields []fieldInfo
}

type packageInfo struct {
	Package string
	Structs []structInfo
}

var primitiveZero = map[string]string{
	"int": "0", "int8": "0", "int16": "0", "int32": "0", "int64": "0",
	"uint": "0", "uint8": "0", "uint16": "0", "uint32": "0", "uint64": "0",
	"uintptr": "0",
	"float32": "0", "float64": "0",
	"complex64": "0", "complex128": "0",
	"string": `""`,
	"bool":   "false",
	"byte":   "0",
	"rune":   "0",
}

const templateStr = `// Code generated by reset generator; DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func (s *{{.Name}}) Reset() {
	if s == nil {
		return
	}
{{range .Fields}}
{{- if eq .Kind "primitive"}}
	s.{{.Name}} = {{.ZeroVal}}
{{- else if eq .Kind "slice"}}
	if s.{{.Name}} != nil {
		s.{{.Name}} = s.{{.Name}}[:0]
	}
{{- else if eq .Kind "map"}}
	clear(s.{{.Name}})
{{- else if eq .Kind "struct"}}
	if resetter, ok := any(&s.{{.Name}}).(interface{ Reset() }); ok {
		resetter.Reset()
	}
{{- else if eq .Kind "pointer"}}
{{- if .IsPrimitive}}
	if s.{{.Name}} != nil {
		*s.{{.Name}} = {{.ZeroVal}}
	}
{{- else}}
	if s.{{.Name}} != nil {
		if resetter, ok := s.{{.Name}}.(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
{{- end}}
{{- end}}
{{- end}}
}
{{end}}`

var tmpl = template.Must(template.New("reset").Parse(templateStr))

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	pkgs, err := walkDir(root)
	if err != nil {
		panic(err)
	}

	for dir, pkg := range pkgs {
		if err := generateFile(dir, pkg); err != nil {
			panic(err)
		}
	}
}

func walkDir(root string) (map[string]*packageInfo, error) {
	pkgs := make(map[string]*packageInfo)
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if name == "vendor" || name == ".git" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		dir := filepath.Dir(path)
		if strings.HasSuffix(filepath.ToSlash(dir), "cmd/reset") {
			return nil
		}

		return parseFile(fset, path, pkgs)
	})

	return pkgs, err
}

func parseFile(fset *token.FileSet, path string, pkgs map[string]*packageInfo) error {
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if !hasGenerateReset(gd.Doc) && !hasGenerateReset(ts.Doc) {
				continue
			}

			si := structInfo{Name: ts.Name.Name}
			for _, field := range st.Fields.List {
				fi := classifyField(field.Type)
				for _, name := range field.Names {
					fi.Name = name.Name
					si.Fields = append(si.Fields, fi)
				}
			}

			if _, exists := pkgs[dir]; !exists {
				pkgs[dir] = &packageInfo{Package: f.Name.Name}
			}
			pkgs[dir].Structs = append(pkgs[dir].Structs, si)
		}
	}

	return nil
}

func classifyField(expr ast.Expr) fieldInfo {
	switch t := expr.(type) {
	case *ast.ArrayType:
		return fieldInfo{Kind: "slice"}
	case *ast.MapType:
		return fieldInfo{Kind: "map"}
	case *ast.StarExpr:
		inner := classifyField(t.X)
		if inner.Kind == "primitive" {
			return fieldInfo{Kind: "pointer", ZeroVal: inner.ZeroVal, IsPrimitive: true}
		}
		return fieldInfo{Kind: "pointer", IsPrimitive: false}
	case *ast.Ident:
		if zv, ok := primitiveZero[t.Name]; ok {
			return fieldInfo{Kind: "primitive", ZeroVal: zv}
		}
		return fieldInfo{Kind: "struct"}
	}
	return fieldInfo{Kind: "primitive", ZeroVal: "0"}
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

func generateFile(dir string, pkg *packageInfo) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkg); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), formatted, 0644)
}
